#!/usr/bin/python2

# import needed modules
import getpass

from ldaphelper import LdapHelper

baseDN = 'dc=zyrenth,dc=com'

manager_dn = "cn=Manager," + baseDN
manager_pass = getpass.getpass("Manager password: ")

server_url = "ldap://localhost:389/"

helper = LdapHelper(server_url, baseDN, manager_dn, manager_pass)
helper.connect()

user = LdapHelper.get_input("User name")
passwd = getpass.getpass("Password: ")
full_name = LdapHelper.get_input("Full name")
home_dir = LdapHelper.get_input("Home directory", '/home/' + user)
shell = LdapHelper.get_input('Login shell', '/bin/bash')

gid = 10000 # ldap-users group

uid = helper.create_user(user, passwd, full_name, gid, home_dir, shell, '')

print("Created user {} ({})".format(user, uid))

helper.close()
